import React from "react";
import ImageGallery from "@/components/ImageGallery";

const images = [
    { src: "/images/tint-job/F62CCD86-DE98-46C6-8125-4D4D37CAA383.JPG", alt: "Image 1" },
    { src: "/images/tint-job/IMG_0143.JPG", alt: "Image 2" },
    { src: "/images/tint-job/IMG_0159.JPG", alt: "Image 3" },
    { src: "/images/tint-job/IMG_0391.JPG", alt: "Image 4" },
    { src: "/images/tint-job/IMG_0494.JPG", alt: "Image 5" },
    { src: "/images/tint-job/IMG_1517.JPG", alt: "Image 6" },
    { src: "/images/tint-job/IMG_1731.JPG", alt: "Image 8" },
    { src: "/images/tint-job/IMG_1738.JPG", alt: "Image 9" },
    { src: "/images/tint-job/IMG_1751.JPG", alt: "Image 10" },
    { src: "/images/tint-job/IMG_2479.JPG", alt: "Image 11" },
    { src: "/images/tint-job/IMG_2717.JPG", alt: "Image 12" },
    { src: "/images/tint-job/IMG_3089.JPG", alt: "Image 15" },
    { src: "/images/tint-job/IMG_3252.JPG", alt: "Image 16" },
    { src: "/images/tint-job/IMG_3823.JPG", alt: "Image 17" },
    { src: "/images/tint-job/IMG_4188.JPG", alt: "Image 18" },
    { src: "/images/tint-job/IMG_4256.jpg", alt: "Image 19" },
    { src: "/images/tint-job/IMG_4257.JPG", alt: "Image 20" },
    { src: "/images/tint-job/IMG_4387.JPG", alt: "Image 21" },
    { src: "/images/tint-job/IMG_4472.JPG", alt: "Image 22" },
    { src: "/images/tint-job/IMG_6056 2.JPG", alt: "Image 23" },
    { src: "/images/tint-job/IMG_6454.JPG", alt: "Image 24" },
    { src: "/images/tint-job/IMG_6805 2.JPG", alt: "Image 25" },
    { src: "/images/tint-job/IMG_7263.JPG", alt: "Image 26" },
    { src: "/images/tint-job/IMG_7378.jpg", alt: "Image 27" },
    { src: "/images/tint-job/IMG_7447.JPG", alt: "Image 28" },
    { src: "/images/tint-job/IMG_7524.JPG", alt: "Image 29" },
    { src: "/images/tint-job/IMG_7595.JPG", alt: "Image 30" },
    { src: "/images/tint-job/IMG_7709.JPG", alt: "Image 31" },
    { src: "/images/tint-job/IMG_7721.JPG", alt: "Image 32" },
    { src: "/images/tint-job/IMG_7756.JPG", alt: "Image 33" },
    { src: "/images/tint-job/IMG_7801.JPG", alt: "Image 34" },
    { src: "/images/tint-job/IMG_7848.JPG", alt: "Image 35" },
    { src: "/images/tint-job/IMG_7886.JPG", alt: "Image 36" },
    { src: "/images/tint-job/IMG_7970.JPG", alt: "Image 37" },
    { src: "/images/tint-job/IMG_8023.JPG", alt: "Image 38" },
    { src: "/images/tint-job/IMG_8234.JPG", alt: "Image 39" },
    { src: "/images/tint-job/IMG_8241.JPG", alt: "Image 40" },
    { src: "/images/tint-job/IMG_8405.JPG", alt: "Image 41" },
    { src: "/images/tint-job/IMG_8428.JPG", alt: "Image 42" },
    { src: "/images/tint-job/IMG_8704.JPG", alt: "Image 43" },
    { src: "/images/tint-job/IMG_8706.JPG", alt: "Image 44" },
    { src: "/images/tint-job/IMG_8744.JPG", alt: "Image 45" },
    { src: "/images/tint-job/IMG_8784.JPG", alt: "Image 46" },
    { src: "/images/tint-job/IMG_8788.JPG", alt: "Image 47" },
    { src: "/images/tint-job/IMG_8804.JPG", alt: "Image 48" },
    { src: "/images/tint-job/IMG_8820.JPG", alt: "Image 49" },
    { src: "/images/tint-job/IMG_8918.JPG", alt: "Image 50" },
    { src: "/images/tint-job/IMG_8940.JPG", alt: "Image 51" },
    { src: "/images/tint-job/IMG_9183.JPG", alt: "Image 52" },
    { src: "/images/tint-job/IMG_9188.JPG", alt: "Image 53" },
    { src: "/images/tint-job/IMG_9276.jpg", alt: "Image 54" },
    { src: "/images/tint-job/IMG_9630.JPG", alt: "Image 55" },
    { src: "/images/tint-job/IMG_9698.JPG", alt: "Image 56" },
    { src: "/images/tint-job/IMG_9701.JPG", alt: "Image 57" },
    { src: "/images/tint-job/IMG_9769.JPG", alt: "Image 58" },
    { src: "/images/tint-job/IMG_9772.JPG", alt: "Image 59" },
    { src: "/images/tint-job/IMG_9792.JPG", alt: "Image 60" },
  ];
  

export default function GalleryPage() {
  return <ImageGallery images={images} />;
}
